### ISSUE TITLE
リセットボタンを押すとボートが消える

### ISSUE THREAD

**Issue by maxazm** [Recursion-TeamE/Connect4#12]
リセットボタンを押す、もしくはリロードするとボードが消える

**Comment by mcnLeandro** [comment]
リセットボタンは解決しましたね！

リロードの方ははデータをデータベースから持ってきていないので、しょうがないです。。。。
でも、ページを表示する際にstoreにデータがあればOK、なければ違うページに遷移。みたいなことはできそうな気がします！

**Comment by mcnLeandro** [comment]
最低限v-ifでデータチェックをするようにしました！
6c3d790bad704b2297d0956b364d380d2a8597be
