### ISSUE TITLE
ボタンを押した後にボタンが使えないようにする

### ISSUE THREAD

**Issue by maxazm** [Recursion-TeamE/Connect4#4]
- [x] mutationにboolean変数を持たせる(e.g. isDropping)
- [x] 落ちている間、isDroppingはtrue
- [x] 変数に応じて表示/非表示を切り替える(v-ifを用いる)
- [x] ベースケースにboolean変数をfalseに切り替える処理を追加

**Comment by mcnLeandro** [comment]
よかったですww
