### ISSUE TITLE
player modeページでplayerの数の手動入力の制限をしないといけない。

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-TeamE/Connect4#7]
https://user-images.githubusercontent.com/72016706/136642369-cfe3ed39-4e70-4431-827d-e0f183a99dc3.mov

- [ ] まず、手動入力だとフォームが動的に増えない
- [x] 制限数を超えた値を設定できてしまう。

**Comment by Acha0203** [comment]
不正な値が入力された場合はアラートを出すように改造してみました。

**Comment by mcnLeandro** [comment]
Select にしましょう！

**Comment by tkwonn** [comment]
Board Sizeの値をユーザーが一度変更してからでないと動的に生成されない
変更した場合、動的に生成される
onChange実装したからだと思います

**Comment by tkwonn** [comment]
Number of Playersラジオボタンで数字の上で連続クリックしたら名前と色が消える

**Comment by tkwonn** [comment]
Board Sizeの値をユーザーが一度変更してからでないと動的に生成されない
変更した場合、動的に生成される
onChangeで関数が実行されるようにしたからだと思います

**Comment by mcnLeandro** [comment]
@tkwonn 
ありがとうございます！

違う問題かなと思うのでそれぞれ新しいissueにしました！

**Comment by Acha0203** [comment]
ラジオボタンの件、了解しました!

**Comment by Acha0203** [comment]
selectにするとこんな感じです。
<img width="303" alt="スクリーンショット 2021-10-10 14 40 47" src="https://user-images.githubusercontent.com/74553433/136683932-a5131ac9-0bfa-46e1-b28a-211c02ed2cb9.png">

**Comment by mcnLeandro** [comment]
ありがとうございます！
これはうまくフォームが動きますか？

**Comment by Acha0203** [comment]
うまく増えますよ!! コードはちょっと煩雑になりましたが…
